[package]
name = "tcpproxy"
version = "0.1.0"
authors = ["Mahmoud Al-Qudsi <mqudsi@neosmart.net>"]
description = "Cross-platform multi-client TCP proxy"
homepage = "https://github.com/neosmart/tcpproxy"
repository = "https://github.com/neosmart/tcpproxy"
readme = "README.md"
keywords = ["proxy", "tcp", "networking"]
categories = ["command-line-utilities", "network-programming"]
license = "MIT"
edition = "2018"

[dependencies]
futures = "0.3.6"
getopts = "0.2.21"
rand = "0.7.3"
tokio = { version = "0.3.1", features = [ "io-util", "net", "rt-multi-thread", "parking_lot", "stream", "macros", ] }
trust-dns-resolver = "0.19.5"
